import Head from "next/head";
import Layout from "@/components/Layout";
import Hero from "@/components/Home/Hero";
import MainAnime from "@/components/Home/MainAnime";

export default function Home() {
  return (
    <>
      <Layout className="bg-primary">
        <Head>
          <title>배경민 포트폴리오</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <section className="flex min-h-100vw flex-col items-center justify-center text-gray-600 body-font">
          <div className="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
            <Hero />
          </div>
        </section>
      </Layout>
    </>
  );
}
