import Layout from "@/components/Layout";
import ProjectItem from "@/components/Projects/ProjectItem";
import Head from "next/head";
import React from "react";
import { TOKEN, DATABASE_ID } from "../config/index";

const Projects = (projects) => {
  console.log(projects.projects.results[0].properties.WorkPeriod.date.start);
  // const date = projecsts.projects.results?.properties;
  return (
    <Layout>
      <Head>
        <title>배경민 포트폴리오</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="flex flex-col items-center">
        {projects.projects.results?.map((aProject) => {
          return <ProjectItem aProject={aProject} key={aProject.id} />;
        })}
      </div>
    </Layout>
  );
};

export default Projects;

export async function getStaticProps() {
  const options = {
    method: "POST",
    headers: {
      accept: "application/json",
      "Notion-Version": "2022-06-28",
      "content-type": "application/json",
      Authorization: `Bearer ${TOKEN}`,
    },
    body: JSON.stringify({
      page_size: 100,
    }),
  };

  const res = await fetch(
    `https://api.notion.com/v1/databases/${DATABASE_ID}/query`,
    options
  );
  const projects = await res.json();

  return {
    props: { projects },
  };
}
