import Layout from "@/components/Layout";
import ProjectItem from "@/components/Projects/ProjectItem";
import Head from "next/head";
import React from "react";
import { TOKEN, DATABASE_ID } from "../config/index";

const Projects = (projects) => {
  console.log(projects, "!!!");
  return (
    <Layout>
      <Head>
        <title>배경민 포트폴리오</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1>총 프로젝트 : {projects.projects.results.length}</h1>
      {projects.projects.results?.map((aProject) => {
        // console.log(aProject.properties.이름.title[0]?.text.content);
        return <ProjectItem aProject={aProject} key={aProject.id} />;
      })}
    </Layout>
  );
};

export default Projects;

export async function getStaticProps() {
  const options = {
    method: "POST",
    headers: {
      accept: "application/json",
      "Notion-Version": "2022-06-28",
      "content-type": "application/json",
      Authorization: `Bearer ${TOKEN}`,
    },
    body: JSON.stringify({
      page_size: 100,
    }),
  };

  const res = await fetch(
    `https://api.notion.com/v1/databases/${DATABASE_ID}/query`,
    options
  );
  const projects = await res.json();

  return {
    props: { projects },
  };
}
