import Layout from "@/components/Layout";
import Head from "next/head";
import React from "react";

const Projects = () => {
  return (
    <Layout>
      <Head>
        <title>배경민 포트폴리오</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1>프로젝트입니다.</h1>
    </Layout>
  );
};

export default Projects;
